apiVersion: batch/v1
kind: Job
metadata:
  generateName: postsync-job
  labels:
    myEnv: {{ .Values.myEnv }}  
  annotations:
    # argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded #, hook-failed
    # helm.sh/resource-policy: keep
spec:
  template:
    spec:
      containers:
        - name: postsync-job
          image: alpine:3.19
          command: 
            - /bin/sh
            - -c
            - |
              echo "PostSync job is running in {{ .Values.myEnv }}";
              sleep 5;  
              
      restartPolicy: Never
  backoffLimit: 2