apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  suspend: false
  template:
    spec:
      containers:
      - name: job-demo
        image: alpine:3.14
        command: ["/bin/sh",  "-c", "i=0; while  [ $i -le 2 ]; do i=$(( i+1 )); echo $i; sleep 5; done"]
      restartPolicy: Never
  backoffLimit: 0
