apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  template:
    spec:
      containers:
      - name: job-demo
        image: alpine:3.14
        command: ["bach",  "-c", "i=0; while  [ $i -le 36 ]; do i=$(( i+1 )); echo $i; sleep 5; done"]
      restartPolicy: Never
  backoffLimit: 0
