apiVersion: batch/v1
kind: Job
metadata:
  generateName: postsync-job
  annotations:
    # argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: postsync-job
          image: alpine:3.19
          command: 
            - /bin/sh
            - -c
            - |
              echo "PostSync job is running";
              sleep 5;  
              
      restartPolicy: Never
  backoffLimit: 2
