apiVersion: batch/v1
kind: Job
metadata:
  generateName: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: presync-job
          image: alpine:3.19
          command: 
            - /bin/sh
            - -c
            - |
              echo "PreSync job is running";
              sleep 3;  
              
      restartPolicy: Never
  backoffLimit: 2
